steps:
- name: ubuntu
  args: ['bash', '-c', "echo '$COMMIT_SHA' > REVISION.txt"]
- name: gcr.io/cloud-builders/gsutil
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'dags'
    - 'gs://asia-northeast1-firewall-ch-b8007ea5-bucket/dags/'
- name: gcr.io/cloud-builders/gsutil
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'dags/'
    - 'gs://asia-northeast1-firewall-ch-b8007ea5-bucket/dags/utils/'
options:
  logging: CLOUD_LOGGING_ONLY